import { productImageUrl } from "./productImage";

const seedCatalog = [
  // Laptops ($100–$300)
  {
    name: "HP 14\" Laptop — Celeron N4020, 4GB RAM, 64GB eMMC",
    description:
      "Budget HP 14-inch notebook. Intel Celeron N4020, 4GB RAM, 64GB storage, Windows 11 Home.",
    price: 120,
    category: "Laptops",
    stock: 18,
    featured: true,
  },
  {
    name: "Asus VivoBook 14 — Pentium Silver, 4GB RAM, 128GB SSD",
    description:
      "Light everyday laptop. Intel Pentium Silver N5030, 4GB RAM, 128GB SSD, 14\" HD display.",
    price: 145,
    category: "Laptops",
    stock: 14,
    featured: false,
  },
  {
    name: "Lenovo IdeaPad 15 — Ryzen 3, 8GB RAM, 256GB SSD",
    description:
      "Reliable student laptop. AMD Ryzen 3 7320U, 8GB RAM, 256GB SSD, 15.6\" Full HD screen.",
    price: 185,
    category: "Laptops",
    stock: 12,
    featured: true,
  },
  {
    name: "Acer Aspire 3 — Core i3, 8GB RAM, 128GB SSD",
    description:
      "Solid daily driver. Intel Core i3-1115G4, 8GB RAM, 128GB SSD, 15.6\" display.",
    price: 220,
    category: "Laptops",
    stock: 10,
    featured: false,
  },
  {
    name: "Dell Latitude Refurb — Core i5, 8GB RAM, 256GB SSD",
    description:
      "Certified refurbished business laptop. Intel Core i5, 8GB RAM, 256GB SSD, 14\" screen.",
    price: 275,
    category: "Laptops",
    stock: 8,
    featured: true,
  },
  {
    name: "Chuwi HeroBook Pro — N100, 8GB RAM, 256GB SSD",
    description:
      "Affordable ultrabook. Intel N100, 8GB RAM, 256GB SSD, 14.1\" Full HD, lightweight build.",
    price: 299,
    category: "Laptops",
    stock: 6,
    featured: false,
  },

  // Smartphones — Samsung ($100–$3000)
  {
    name: "Samsung Galaxy A05 — 4GB RAM, 64GB",
    description: "Entry Samsung smartphone. 6.7\" display, 50MP camera, 5000mAh battery.",
    price: 100,
    category: "Smartphones",
    stock: 40,
    featured: false,
  },
  {
    name: "Samsung Galaxy A15 — 6GB RAM, 128GB",
    description: "Budget Galaxy with AMOLED screen, 50MP triple camera, and fast charging.",
    price: 165,
    category: "Smartphones",
    stock: 35,
    featured: true,
  },
  {
    name: "Samsung Galaxy A25 — 8GB RAM, 128GB",
    description: "Mid-range Galaxy. Super AMOLED 6.5\", 50MP OIS camera, 5000mAh battery.",
    price: 220,
    category: "Smartphones",
    stock: 28,
    featured: false,
  },
  {
    name: "Samsung Galaxy A55 — 8GB RAM, 256GB",
    description: "Premium mid-range. Exynos chip, 6.6\" AMOLED 120Hz, IP67 water resistance.",
    price: 380,
    category: "Smartphones",
    stock: 22,
    featured: true,
  },
  {
    name: "Samsung Galaxy S23 — 8GB RAM, 256GB",
    description: "Flagship Samsung. Snapdragon chip, 6.1\" Dynamic AMOLED, triple 50MP cameras.",
    price: 650,
    category: "Smartphones",
    stock: 15,
    featured: false,
  },
  {
    name: "Samsung Galaxy S24 — 8GB RAM, 256GB",
    description: "Latest Galaxy S series. AI features, 6.2\" AMOLED 120Hz, all-day battery.",
    price: 850,
    category: "Smartphones",
    stock: 12,
    featured: true,
  },
  {
    name: "Samsung Galaxy S24 Ultra — 12GB RAM, 512GB",
    description: "Top-tier Samsung. S Pen built-in, 200MP camera, titanium frame, 6.8\" display.",
    price: 1250,
    category: "Smartphones",
    stock: 8,
    featured: true,
  },
  {
    name: "Samsung Galaxy Z Flip 5 — 8GB RAM, 256GB",
    description: "Foldable flip phone. Compact design, FlexCam, 6.7\" inner AMOLED display.",
    price: 980,
    category: "Smartphones",
    stock: 6,
    featured: false,
  },

  // Smartphones — iPhone ($100–$3000)
  {
    name: "iPhone SE (2022) — 64GB",
    description: "Compact Apple phone. A15 Bionic chip, 4.7\" Retina display, Touch ID.",
    price: 180,
    category: "Smartphones",
    stock: 20,
    featured: false,
  },
  {
    name: "iPhone 12 — 64GB",
    description: "Classic iPhone design. A14 Bionic, 6.1\" Super Retina XDR, dual 12MP cameras.",
    price: 320,
    category: "Smartphones",
    stock: 18,
    featured: false,
  },
  {
    name: "iPhone 13 — 128GB",
    description: "Popular iPhone. A15 Bionic, 6.1\" display, improved battery and cameras.",
    price: 450,
    category: "Smartphones",
    stock: 16,
    featured: true,
  },
  {
    name: "iPhone 14 — 128GB",
    description: "Reliable iPhone. A15 Bionic, 6.1\" display, crash detection, great cameras.",
    price: 620,
    category: "Smartphones",
    stock: 14,
    featured: false,
  },
  {
    name: "iPhone 15 — 128GB",
    description: "USB-C iPhone. A16 Bionic, 6.1\" display, 48MP main camera, Dynamic Island.",
    price: 780,
    category: "Smartphones",
    stock: 12,
    featured: true,
  },
  {
    name: "iPhone 15 Pro — 256GB",
    description: "Pro titanium iPhone. A17 Pro chip, Action Button, 48MP Pro camera system.",
    price: 1100,
    category: "Smartphones",
    stock: 10,
    featured: false,
  },
  {
    name: "iPhone 15 Pro Max — 256GB",
    description: "Large Pro iPhone. 6.7\" display, 5x optical zoom, all-day battery life.",
    price: 1350,
    category: "Smartphones",
    stock: 8,
    featured: true,
  },
  {
    name: "iPhone 16 Pro Max — 512GB",
    description: "Latest flagship iPhone. A18 Pro, 6.9\" display, best-in-class camera and battery.",
    price: 2800,
    category: "Smartphones",
    stock: 5,
    featured: true,
  },

  // Bluetooth speakers
  {
    name: "Oraimo OBS-53 Mini Bluetooth Speaker",
    description: "Pocket-size wireless speaker. 10W output, 12-hour playtime, IPX5 splash proof.",
    price: 35,
    category: "Bluetooth Speakers",
    stock: 60,
    featured: false,
  },
  {
    name: "JBL Go 3 Portable Speaker",
    description: "Compact JBL speaker with bold sound, IP67 waterproof, 5-hour battery.",
    price: 45,
    category: "Bluetooth Speakers",
    stock: 45,
    featured: true,
  },
  {
    name: "Sony SRS-XB100 Bluetooth Speaker",
    description: "Extra Bass portable speaker. Clear sound, strap loop, up to 16 hours playback.",
    price: 55,
    category: "Bluetooth Speakers",
    stock: 38,
    featured: false,
  },
  {
    name: "Anker Soundcore 2 Speaker",
    description: "Best-selling budget speaker. 24-hour battery, IPX7 waterproof, stereo sound.",
    price: 65,
    category: "Bluetooth Speakers",
    stock: 50,
    featured: true,
  },
  {
    name: "Tribit StormBox Micro Speaker",
    description: "Tiny rugged speaker. IP67 rated, 8-hour battery, surprisingly loud for its size.",
    price: 50,
    category: "Bluetooth Speakers",
    stock: 42,
    featured: false,
  },

  // Chargers
  {
    name: "USB-C 20W Wall Charger",
    description: "Fast wall adapter for phones and tablets. Compact plug, universal USB-C port.",
    price: 12,
    category: "Chargers",
    stock: 120,
    featured: false,
  },
  {
    name: "Car Dual USB Charger 3.4A",
    description: "In-car charger with two USB ports. Works with iPhone and Android cables.",
    price: 10,
    category: "Chargers",
    stock: 90,
    featured: false,
  },
  {
    name: "Samsung 25W Super Fast Charger",
    description: "Official-style Samsung fast charger with USB-C cable. Charges Galaxy in minutes.",
    price: 18,
    category: "Chargers",
    stock: 75,
    featured: false,
  },
  {
    name: "Apple 20W USB-C Power Adapter",
    description: "Fast charge for iPhone and iPad. Original-spec 20W USB-C wall adapter.",
    price: 22,
    category: "Chargers",
    stock: 65,
    featured: true,
  },
  {
    name: "3-in-1 Wireless Charging Pad",
    description: "Charge phone, earbuds, and watch on one pad. 15W fast wireless charging.",
    price: 28,
    category: "Chargers",
    stock: 55,
    featured: false,
  },
  {
    name: "10000mAh Power Bank — USB-C PD",
    description: "Slim portable battery. 10000mAh capacity, 18W fast charge in and out.",
    price: 25,
    category: "Chargers",
    stock: 80,
    featured: true,
  },
  {
    name: "3-in-1 Charging Cable Kit",
    description: "One cable with Lightning, USB-C, and Micro-USB tips. 1.2m braided cord.",
    price: 15,
    category: "Chargers",
    stock: 100,
    featured: false,
  },

  // Earphones, earbuds & AirPods
  {
    name: "Wired Earphones with Mic — 3.5mm",
    description: "Basic in-ear earphones. Inline mic and remote, compatible with most phones.",
    price: 8,
    category: "Earphones & Earbuds",
    stock: 150,
    featured: false,
  },
  {
    name: "Sony MDR-E9LP Wired Earphones",
    description: "Lightweight Sony earphones. 13.5mm drivers, comfortable fit, clear sound.",
    price: 15,
    category: "Earphones & Earbuds",
    stock: 80,
    featured: false,
  },
  {
    name: "Oraimo FreePods Lite Earbuds",
    description: "Budget true wireless earbuds. Touch controls, 20-hour total battery.",
    price: 20,
    category: "Earphones & Earbuds",
    stock: 70,
    featured: true,
  },
  {
    name: "Apple EarPods — Lightning",
    description: "Classic Apple wired earphones with Lightning connector and built-in remote.",
    price: 25,
    category: "Earphones & Earbuds",
    stock: 60,
    featured: false,
  },
  {
    name: "Xiaomi Redmi Buds 4 Earbuds",
    description: "Affordable ANC earbuds. 35-hour battery, IP54 rating, clear call quality.",
    price: 35,
    category: "Earphones & Earbuds",
    stock: 55,
    featured: false,
  },
  {
    name: "JBL Tune 510BT Wireless Earphones",
    description: "On-ear Bluetooth headphones. JBL Pure Bass, 40-hour battery, foldable design.",
    price: 45,
    category: "Earphones & Earbuds",
    stock: 40,
    featured: false,
  },
  {
    name: "Samsung Galaxy Buds FE",
    description: "Samsung wireless earbuds. Active noise cancellation, 8-hour playtime per charge.",
    price: 85,
    category: "Earphones & Earbuds",
    stock: 35,
    featured: true,
  },
  {
    name: "Apple AirPods (2nd Gen)",
    description: "Classic Apple AirPods. Easy setup, Siri access, 5-hour listening on one charge.",
    price: 120,
    category: "Earphones & Earbuds",
    stock: 30,
    featured: true,
  },
  {
    name: "Apple AirPods Pro (2nd Gen)",
    description: "Premium Apple earbuds. Active noise cancellation, Adaptive Audio, USB-C case.",
    price: 220,
    category: "Earphones & Earbuds",
    stock: 22,
    featured: true,
  },

  // Storage
  {
    name: "SanDisk 32GB USB Flash Drive",
    description: "Basic USB 2.0 thumb drive for documents, photos, and file transfers.",
    price: 8,
    category: "Storage",
    stock: 200,
    featured: false,
  },
  {
    name: "SanDisk 64GB USB 3.0 Flash Drive",
    description: "Fast USB 3.0 drive. Transfer movies and backups quickly on any PC.",
    price: 12,
    category: "Storage",
    stock: 150,
    featured: false,
  },
  {
    name: "Kingston 128GB USB Flash Drive",
    description: "High-capacity USB 3.2 drive. Reliable storage for work and school files.",
    price: 18,
    category: "Storage",
    stock: 100,
    featured: true,
  },
  {
    name: "Samsung 256GB microSD Card",
    description: "Expand phone or camera storage. U3 speed class, up to 130MB/s read.",
    price: 22,
    category: "Storage",
    stock: 90,
    featured: false,
  },
  {
    name: "32GB OTG USB for Android Phones",
    description: "Dual USB and micro-USB/OTG drive. Move files between phone and PC easily.",
    price: 10,
    category: "Storage",
    stock: 120,
    featured: false,
  },
  {
    name: "SanDisk 1TB External HDD",
    description: "Portable hard drive for backups. USB 3.0, slim design, plug-and-play.",
    price: 55,
    category: "Storage",
    stock: 45,
    featured: true,
  },
  {
    name: "Samsung T7 500GB Portable SSD",
    description: "Fast external SSD. Up to 1050MB/s read, USB-C, shock-resistant metal body.",
    price: 65,
    category: "Storage",
    stock: 38,
    featured: false,
  },

  // Cheap gadgets
  {
    name: "Selfie Ring Light Clip",
    description: "Clip-on LED ring light for video calls and selfies. 3 brightness levels.",
    price: 12,
    category: "Gadgets",
    stock: 80,
    featured: false,
  },
  {
    name: "Phone Pop Socket Grip",
    description: "Collapsible phone grip and stand. Better hold for texting and watching videos.",
    price: 5,
    category: "Gadgets",
    stock: 200,
    featured: false,
  },
  {
    name: "Bluetooth Remote Shutter",
    description: "Wireless camera button for selfies and group photos. Pairs with iPhone and Android.",
    price: 8,
    category: "Gadgets",
    stock: 90,
    featured: false,
  },
  {
    name: "Phone Tripod Stand",
    description: "Adjustable mini tripod with phone clip. Great for TikTok, vlogs, and video calls.",
    price: 18,
    category: "Gadgets",
    stock: 55,
    featured: true,
  },
  {
    name: "USB-C to HDMI Adapter",
    description: "Mirror your phone or laptop to a TV or monitor. Plug-and-play, no drivers needed.",
    price: 14,
    category: "Gadgets",
    stock: 65,
    featured: false,
  },
  {
    name: "Tempered Glass Screen Protector (2-Pack)",
    description: "Universal phone screen protectors. Easy install kit included.",
    price: 6,
    category: "Gadgets",
    stock: 250,
    featured: false,
  },
  {
    name: "Silicone Phone Case — Universal Fit",
    description: "Soft flexible case with raised edges. Available for most popular phone sizes.",
    price: 9,
    category: "Gadgets",
    stock: 180,
    featured: false,
  },
  {
    name: "Mini USB Desk Fan",
    description: "Quiet personal fan powered by USB. Perfect for desk, bedside, or travel.",
    price: 15,
    category: "Gadgets",
    stock: 70,
    featured: false,
  },
  {
    name: "LED Desk Lamp — USB Powered",
    description: "Adjustable gooseneck lamp with 3 color modes. Plugs into laptop or power bank.",
    price: 16,
    category: "Gadgets",
    stock: 60,
    featured: false,
  },
  {
    name: "Smartwatch Silicone Band",
    description: "Replacement strap for 38–44mm smartwatches. Sweat-proof and comfortable.",
    price: 11,
    category: "Gadgets",
    stock: 85,
    featured: false,
  },
];

export const seedProducts = seedCatalog.map((product) => ({
  ...product,
  image: productImageUrl(product.name),
}));
